sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: k/+XoYWK4Py1jZ3cs617EW9jHNnmlz/v2ykCa84HChvR95MzjDj7sB2/rs7BdfLPmDwzwo/4xQg00LUVjHqhKIR+sHOhuPXxilLqedIBFd/LDSg4blbIcyPmRzLSlLyMbss5CkzA8UTtw8UczfysLYfgVXQbnZ0Lcej4c6ZSsdAQgDVtcDN3aoct4XpizbfYoh4tocob7AN0k5pbxbEUkY3RyLeYn+BolYfUs8b3kvqmNpfsq5T1zu6mphvZ3IJfuft4NXwZxusvv/u+oqjz+3jsvk+ewDBCwHaioGnznmfx0Jq2+twkfzNZyg5+m2OPCRR+oIHdHxKgjQ1sCxDL249XOiiiWxJtefpOLW97OzUkPjgbcdWo64vLxrMbq7YbkLWAz4v3wPOP3yl0bfnfwhktkz+pvG/1GoSfBQFoIVautYXZ7NGDoro2MfQ1yHDvysJ/g6qHZ+iz/afsNQSwGMZLepUj/DguETdCr3G1e95vB7/ECuSYDSw496PaOGikQwuiPOjcN5kR5MouG5ZsjIv5gjAqbNOn/TPWGuj/grUjtmA6hbzxtp/xlyYgCo0eFMAzZ2JKBKutHGizll6DqUP2TkZWhEw3ILMGIh5QiMc0FXa6ujDtYNKhhVZZBBrGpUwO2pEOjGyXrq4+ZADXUKnN6KUbMUZ1X4fLhKbH9jw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Passion-in-the-Desert_1555
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy